const Companies = [
  {
    company: "KamilKoç",
    icon_uri:
      "https://cdn-cf.cms.flixbus.com/drupal-assets/ogimage/kamilkoc.png",
  },
  {
    company: "Metro Turizm",
    icon_uri:
      "https://cvbenim.com/firma/logo/240_metro_turizm_seyahat_organizas_m75eSal2sD_7187.png",
  },
];

const TicketsInfo = [
  {
    id: 1,
    departure: "1",
    destination: "2",
    departureName: "Istanbul",
    destinationName: "Ankara",
    dateOfDeparture: "2023/07/15",
    timeOfDeparture: "14:00",
    timeOfDestination: "19:00",
    pricePerTicket: 400,
    company: Companies[0].company,
    icon: Companies[0].icon_uri,
    seats: [
      {
        id: 1,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 2,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 3,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 4,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 5,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 6,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 7,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 8,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 9,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 10,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 11,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 12,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 13,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 14,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 15,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 16,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 17,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 18,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 19,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 20,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 21,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 22,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 23,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 24,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 25,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 26,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 27,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 28,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 29,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 30,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 31,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 32,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 33,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 34,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 35,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 36,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 37,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 38,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 39,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 40,
        available: 0,
        gender: "female",
        selected: false,
      },
    ],
  },
  {
    id: 2,
    departure: "1",
    destination: "3",
    departureName: "Istanbul",
    destinationName: "Izmir",
    dateOfDeparture: "2023/07/15",
    timeOfDeparture: "17:00",
    timeOfDestination: "21:00",
    pricePerTicket: 500,
    company: Companies[1].company,
    icon: Companies[1].icon_uri,
    seats: [
      {
        id: 1,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 2,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 3,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 4,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 5,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 6,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 7,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 8,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 9,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 10,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 11,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 12,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 13,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 14,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 15,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 16,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 17,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 18,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 19,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 20,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 21,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 22,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 23,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 24,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 25,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 26,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 27,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 28,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 29,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 30,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 31,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 32,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 33,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 34,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 35,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 36,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 37,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 38,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 39,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 40,
        available: 0,
        gender: "female",
        selected: false,
      },
    ],
  },
  {
    id: 3,
    departure: "1",
    destination: "2",
    departureName: "Istanbul",
    destinationName: "Ankara",
    dateOfDeparture: "2023/07/15",
    timeOfDeparture: "10:00",
    timeOfDestination: "15:00",
    pricePerTicket: 375,
    company: Companies[1].company,
    icon: Companies[1].icon_uri,
    seats: [
      {
        id: 1,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 2,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 3,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 4,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 5,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 6,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 7,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 8,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 9,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 10,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 11,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 12,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 13,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 14,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 15,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 16,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 17,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 18,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 19,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 20,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 21,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 22,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 23,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 24,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 25,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 26,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 27,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 28,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 29,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 30,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 31,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 32,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 33,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 34,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 35,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 36,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 37,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 38,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 39,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 40,
        available: 0,
        gender: "female",
        selected: false,
      },
    ],
  },
  {
    id: 4,
    departure: "1",
    destination: "3",
    departureName: "Istanbul",
    destinationName: "Izmir",
    dateOfDeparture: "2023/07/15",
    timeOfDeparture: "12:00",
    timeOfDestination: "16:00",
    pricePerTicket: 550,
    company: Companies[0].company,
    icon: Companies[0].icon_uri,
    seats: [
      {
        id: 1,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 2,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 3,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 4,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 5,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 6,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 7,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 8,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 9,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 10,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 11,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 12,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 13,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 14,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 15,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 16,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 17,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 18,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 19,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 20,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 21,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 22,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 23,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 24,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 25,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 26,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 27,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 28,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 29,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 30,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 31,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 32,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 33,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 34,
        available: 0,
        gender: "female",
        selected: false,
      },
      {
        id: 35,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 36,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 37,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 38,
        available: 1,
        gender: "",
        selected: false,
      },
      {
        id: 39,
        available: 0,
        gender: "male",
        selected: false,
      },
      {
        id: 40,
        available: 0,
        gender: "female",
        selected: false,
      },
    ],
  },
];

export default TicketsInfo;
